default_context:
  project_name: 'BioSegment'
  project_slug: 'biosegment'
  domain_main: 'biosegment.irc.ugent.be'
  domain_staging: 'stag.biosegment.irc.ugent.be'
  docker_swarm_stack_name_main: 'biosegment-irc-ugent-be'
  docker_swarm_stack_name_staging: 'stag-biosegment-irc-ugent-be'
  secret_key: '0b415a389d599de566ee2052e6aabdbb23317cd810dc6dfbdec53af9221819f7'
  first_superuser: 'admin@biosegment.irc.ugent.be'
  first_superuser_password: 'm1cr0scopy'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.biosegment.irc.ugent.be", "https://stag.biosegment.irc.ugent.be", "https://biosegment.irc.ugent.be", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@biosegment.irc.ugent.be'
  postgres_password: 'm1cr0scopy'
  pgadmin_default_user: 'admin@biosegment.irc.ugent.be'
  pgadmin_default_user_password: 'm1cr0scopy'
  traefik_constraint_tag: 'biosegment.irc.ugent.be'
  traefik_constraint_tag_staging: 'stag.biosegment.irc.ugent.be'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:m1cr0scopy'
  sentry_dsn: ''
  docker_image_prefix: 'biosegment'
  docker_image_backend: 'biosegmentbackend'
  docker_image_celeryworker: 'biosegmentceleryworker'
  docker_image_frontend: 'biosegmentfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
